In [10]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('y_train.csv')

In [12]:
n = len(df)

In [13]:
ans = [0 for i in range(n)]

In [14]:
df = pd.DataFrame(data=ans, columns=[['FGM']])

In [15]:
df.to_csv('y_pred.csv', index=False)

       FGM
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
...    ...
52369    0
52370    0
52371    0
52372    0
52373    0
52374    0
52375    0
52376    0
52377    0
52378    0
52379    0
52380    0
52381    0
52382    0
52383    0
52384    0
52385    0
52386    0
52387    0
52388    0
52389    0
52390    0
52391    0
52392    0
52393    0
52394    0
52395    0
52396    0
52397    0
52398    0

[52399 rows x 1 columns]